//! LLM-distilled semantic meaning per vocabulary term.
//!
//! Each vocab entry gets a 1-2 sentence description of what it refers to and
//! the contexts it applies in. Generated by Groq from observed example
//! sentences and refined as more examples accumulate. The polish prompt then
//! includes this meaning per entry, enabling the LLM to do SEMANTIC
//! alignment (does the transcript context match the term's meaning?) instead
//! of inferring from a single example each call.
//!
//! Design constraints:
//!   • CHEAP — uses Groq llama-3.1-8b-instant (~50ms, ~$0.0001 per call)
//!   • ASYNC — fire-and-forget; never blocks the user-visible learning toast
//!   • GRACEFUL — on API failure returns None, term still works without meaning
//!   • CAPPED — meaning capped at 280 chars (~70 tokens) to keep prompt bounded
//!
//! Two entrypoints:
//!   • `generate_initial(term, example)` — first-time generation from one
//!     example. Used immediately on promotion.
//!   • `refine(term, current_meaning, examples)` — refresh after K=3 new
//!     examples accumulate. LLM keeps what's still accurate, expands or
//!     corrects from the new contexts.

use reqwest::Client;
use serde::Deserialize;
use serde_json::json;
use tracing::{info, warn};

const GROQ_ENDPOINT:   &str = "https://api.groq.com/openai/v1/chat/completions";
const OPENAI_ENDPOINT: &str = "https://api.openai.com/v1/chat/completions";
const MEANING_MODEL:   &str = "llama-3.1-8b-instant";
/// Used only when Groq is unreachable. gpt-4.1-nano is the smallest, cheapest
/// OpenAI chat model — comparable cost to Groq and ~150–300 ms latency.
const OPENAI_FALLBACK_MODEL: &str = "gpt-4.1-nano";
const MAX_MEANING_CHARS: usize = 280;

/// Generate the initial meaning for a freshly-promoted vocab term.
///
/// `term` is the canonical spelling. `example` is the sentence the term was
/// first observed in (`vocabulary.example_context`).
///
/// Two-stage fallback: try Groq first (cheap + fast); if it returns None for
/// any reason (no key, network error, parse failure, empty content), fall
/// back to OpenAI gpt-4.1-nano via `OPENAI_API_KEY`. If both fail, returns
/// None and the caller leaves `meaning` NULL (the polish prompt then filters
/// the term out — see `select_for_polish_hybrid`).
///
/// The caller persists the result via `vocabulary::update_meaning()`.
pub async fn generate_initial(
    client:      &Client,
    groq_key:    &str,
    openai_key:  &str,
    term:        &str,
    example:     &str,
) -> Option<String> {
    let user_message = format!(
        "TERM: {term}\n\
         EXAMPLE SENTENCE: \"{example}\"\n\n\
         Write a 1-2 sentence description of what this term refers to and the \
         contexts it appears in. Be specific to what the example tells you. \
         Don't speculate beyond what the example demonstrates. If the example \
         doesn't make the meaning clear, say so plainly."
    );
    call_with_fallback(client, groq_key, openai_key, &user_message, term).await
}

/// Refresh an existing meaning given the current meaning + observed examples.
///
/// The LLM is told to KEEP what's still accurate and EXPAND or CORRECT based
/// on new contexts. This handles term-meaning evolution as the user uses the
/// term in more diverse situations over time.
pub async fn refine(
    client:           &Client,
    groq_key:         &str,
    openai_key:       &str,
    term:             &str,
    current_meaning:  &str,
    examples:         &[String],
) -> Option<String> {
    if examples.is_empty() {
        return Some(current_meaning.to_string());
    }

    let examples_block = examples
        .iter()
        .take(10)
        .enumerate()
        .map(|(i, e)| format!("  {}. \"{}\"", i + 1, e.trim()))
        .collect::<Vec<_>>()
        .join("\n");

    let user_message = format!(
        "TERM: {term}\n\
         CURRENT DESCRIPTION: \"{current_meaning}\"\n\n\
         RECENT EXAMPLES (most recent first):\n{examples_block}\n\n\
         Update the description to capture the meaning across all observed \
         contexts. Keep what's still accurate. Expand or correct based on \
         new contexts that the current description doesn't cover. Output ONLY \
         the updated 1-2 sentence description, nothing else."
    );
    call_with_fallback(client, groq_key, openai_key, &user_message, term).await
}

#[derive(Deserialize)]
struct GroqResponse {
    choices: Vec<GroqChoice>,
}
#[derive(Deserialize)]
struct GroqChoice {
    message: GroqMessage,
}
#[derive(Deserialize)]
struct GroqMessage {
    content: String,
}

const SYSTEM_PROMPT: &str = "You are a vocabulary describer. Given a term and \
example sentences, you write tight 1-2 sentence descriptions of what the term \
means and what contexts it appears in. You are specific, you don't speculate, \
and you output ONLY the description — no preamble, no formatting, no quotes \
around the answer.";

/// Try Groq first; on any failure fall back to OpenAI gpt-4.1-nano. Returns
/// None only when both providers are unreachable / fail / return empty.
/// `term` is included for diagnostic logging so we can tell which provider
/// served which term.
async fn call_with_fallback(
    client:      &Client,
    groq_key:    &str,
    openai_key:  &str,
    user_message: &str,
    term:        &str,
) -> Option<String> {
    if !groq_key.is_empty() {
        if let Some(text) = call_chat_completions(
            client, GROQ_ENDPOINT, groq_key, MEANING_MODEL, user_message, "groq",
        ).await {
            info!("[meaning] {term:?} ← groq");
            return Some(text);
        }
        warn!("[meaning] groq failed for {term:?} — trying openai fallback");
    }
    if !openai_key.is_empty() {
        if let Some(text) = call_chat_completions(
            client, OPENAI_ENDPOINT, openai_key, OPENAI_FALLBACK_MODEL, user_message, "openai",
        ).await {
            info!("[meaning] {term:?} ← openai (fallback)");
            return Some(text);
        }
        warn!("[meaning] openai fallback also failed for {term:?}");
    } else if groq_key.is_empty() {
        warn!("[meaning] no groq key AND no openai key — meaning will stay NULL for {term:?}");
    }
    None
}

/// Standard OpenAI-compatible Chat Completions call — works for both Groq
/// and OpenAI since Groq exposes the OpenAI-compatible endpoint shape.
async fn call_chat_completions(
    client:        &Client,
    endpoint:      &str,
    api_key:       &str,
    model:         &str,
    user_message:  &str,
    provider_tag:  &str,
) -> Option<String> {
    let body = json!({
        "model":       model,
        "temperature": 0.2,
        "max_tokens":  120,
        "messages": [
            { "role": "system", "content": SYSTEM_PROMPT },
            { "role": "user",   "content": user_message },
        ],
    });

    let t0 = std::time::Instant::now();
    let resp = match client
        .post(endpoint)
        .header("Authorization", format!("Bearer {api_key}"))
        .header("Content-Type", "application/json")
        .json(&body)
        .timeout(std::time::Duration::from_secs(8))
        .send()
        .await
    {
        Ok(r) => r,
        Err(e) => {
            warn!("[meaning] {provider_tag} request failed: {e}");
            return None;
        }
    };
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        let preview = &body[..body.len().min(200)];
        warn!("[meaning] {provider_tag} returned {status}: {preview}");
        return None;
    }
    let parsed: GroqResponse = match resp.json().await {
        Ok(p) => p,
        Err(e) => {
            warn!("[meaning] {provider_tag} response parse failed: {e}");
            return None;
        }
    };
    let content = parsed.choices.first()
        .map(|c| c.message.content.trim().to_string())
        .unwrap_or_default();

    if content.is_empty() {
        warn!("[meaning] {provider_tag} returned empty content");
        return None;
    }

    let capped: String = if content.chars().count() > MAX_MEANING_CHARS {
        content.chars().take(MAX_MEANING_CHARS).collect::<String>() + "…"
    } else {
        content
    };

    info!(
        "[meaning] {provider_tag} generated in {}ms ({} chars)",
        t0.elapsed().as_millis(), capped.len(),
    );
    Some(capped)
}
