//! LLM-distilled semantic meaning per vocabulary term.
//!
//! Each vocab entry gets a 1-2 sentence description of what it refers to and
//! the contexts it applies in. Generated by Groq from observed example
//! sentences and refined as more examples accumulate. The polish prompt then
//! includes this meaning per entry, enabling the LLM to do SEMANTIC
//! alignment (does the transcript context match the term's meaning?) instead
//! of inferring from a single example each call.
//!
//! Design constraints:
//!   • CHEAP — uses Groq llama-3.1-8b-instant (~50ms, ~$0.0001 per call)
//!   • ASYNC — fire-and-forget; never blocks the user-visible learning toast
//!   • GRACEFUL — on API failure returns None, term still works without meaning
//!   • CAPPED — meaning capped at 280 chars (~70 tokens) to keep prompt bounded
//!
//! Two entrypoints:
//!   • `generate_initial(term, example)` — first-time generation from one
//!     example. Used immediately on promotion.
//!   • `refine(term, current_meaning, examples)` — refresh after K=3 new
//!     examples accumulate. LLM keeps what's still accurate, expands or
//!     corrects from the new contexts.

use reqwest::Client;
use serde::Deserialize;
use serde_json::json;
use tracing::{info, warn};

const GROQ_ENDPOINT: &str = "https://api.groq.com/openai/v1/chat/completions";
const MEANING_MODEL: &str = "llama-3.1-8b-instant";
const MAX_MEANING_CHARS: usize = 280;

/// Generate the initial meaning for a freshly-promoted vocab term.
///
/// `term` is the canonical spelling. `example` is the sentence the term was
/// first observed in (`vocabulary.example_context`). Returns `None` when:
///   • API key is empty
///   • API returns an error
///   • Response can't be parsed
///   • Returned text is empty after trimming
///
/// The caller persists the result via `vocabulary::update_meaning()`.
pub async fn generate_initial(
    client:  &Client,
    api_key: &str,
    term:    &str,
    example: &str,
) -> Option<String> {
    if api_key.is_empty() {
        warn!("[meaning] no Groq API key — skipping generation for {term:?}");
        return None;
    }

    let user_message = format!(
        "TERM: {term}\n\
         EXAMPLE SENTENCE: \"{example}\"\n\n\
         Write a 1-2 sentence description of what this term refers to and the \
         contexts it appears in. Be specific to what the example tells you. \
         Don't speculate beyond what the example demonstrates. If the example \
         doesn't make the meaning clear, say so plainly."
    );
    call_groq(client, api_key, &user_message).await
}

/// Refresh an existing meaning given the current meaning + observed examples.
///
/// The LLM is told to KEEP what's still accurate and EXPAND or CORRECT based
/// on new contexts. This handles term-meaning evolution as the user uses the
/// term in more diverse situations over time.
pub async fn refine(
    client:           &Client,
    api_key:          &str,
    term:             &str,
    current_meaning:  &str,
    examples:         &[String],
) -> Option<String> {
    if api_key.is_empty() { return None; }
    if examples.is_empty() {
        return Some(current_meaning.to_string());
    }

    let examples_block = examples
        .iter()
        .take(10)
        .enumerate()
        .map(|(i, e)| format!("  {}. \"{}\"", i + 1, e.trim()))
        .collect::<Vec<_>>()
        .join("\n");

    let user_message = format!(
        "TERM: {term}\n\
         CURRENT DESCRIPTION: \"{current_meaning}\"\n\n\
         RECENT EXAMPLES (most recent first):\n{examples_block}\n\n\
         Update the description to capture the meaning across all observed \
         contexts. Keep what's still accurate. Expand or correct based on \
         new contexts that the current description doesn't cover. Output ONLY \
         the updated 1-2 sentence description, nothing else."
    );
    call_groq(client, api_key, &user_message).await
}

#[derive(Deserialize)]
struct GroqResponse {
    choices: Vec<GroqChoice>,
}
#[derive(Deserialize)]
struct GroqChoice {
    message: GroqMessage,
}
#[derive(Deserialize)]
struct GroqMessage {
    content: String,
}

const SYSTEM_PROMPT: &str = "You are a vocabulary describer. Given a term and \
example sentences, you write tight 1-2 sentence descriptions of what the term \
means and what contexts it appears in. You are specific, you don't speculate, \
and you output ONLY the description — no preamble, no formatting, no quotes \
around the answer.";

async fn call_groq(client: &Client, api_key: &str, user_message: &str) -> Option<String> {
    let body = json!({
        "model":       MEANING_MODEL,
        "temperature": 0.2,
        "max_tokens":  120,
        "messages": [
            { "role": "system", "content": SYSTEM_PROMPT },
            { "role": "user",   "content": user_message },
        ],
    });

    let t0 = std::time::Instant::now();
    let resp = match client
        .post(GROQ_ENDPOINT)
        .header("Authorization", format!("Bearer {api_key}"))
        .header("Content-Type", "application/json")
        .json(&body)
        .timeout(std::time::Duration::from_secs(8))
        .send()
        .await
    {
        Ok(r) => r,
        Err(e) => {
            warn!("[meaning] Groq request failed: {e}");
            return None;
        }
    };
    if !resp.status().is_success() {
        warn!("[meaning] Groq returned non-success: {}", resp.status());
        return None;
    }
    let parsed: GroqResponse = match resp.json().await {
        Ok(p) => p,
        Err(e) => {
            warn!("[meaning] Groq response parse failed: {e}");
            return None;
        }
    };
    let content = parsed.choices.first()
        .map(|c| c.message.content.trim().to_string())
        .unwrap_or_default();

    if content.is_empty() {
        warn!("[meaning] Groq returned empty content");
        return None;
    }

    // Cap to keep polish prompt bounded.
    let capped: String = if content.chars().count() > MAX_MEANING_CHARS {
        content.chars().take(MAX_MEANING_CHARS).collect::<String>() + "…"
    } else {
        content
    };

    info!("[meaning] generated in {}ms ({} chars)", t0.elapsed().as_millis(), capped.len());
    Some(capped)
}
