//! Vocabulary store — STT-layer bias terms.
//!
//! These are correctly-spelled terms (jargon, names, brands, code identifiers)
//! that we want the STT engine to recognize.  At recording start we load the
//! top-N by weight and inject them into the STT request — Deepgram's `keyterm`
//! parameter for nova-3, Whisper's `initial_prompt` for OSS Whisper.
//!
//! Promotion paths (handled in `routes::classify`):
//!   • STT_ERROR classification with jargon-like candidate → auto-add (weight=1.0)
//!   • Repeat sighting of an existing term                  → bump weight
//!   • Manual user star (UI)                                → weight=2.0, source='starred'
//!
//! Decay: callers may periodically halve weights of terms not used in N days.
//! This module exposes the primitives; the schedule is policy elsewhere.

use rusqlite::params;
use serde::Serialize;
use tracing::info;

use super::{DbPool, now_ms};

#[derive(Debug, Clone, Serialize)]
pub struct VocabTerm {
    pub term: String,
    pub weight: f64,
    pub use_count: i64,
    pub last_used: i64,
    pub source: String,
    /// Optional sentence-or-snippet the term was first observed in. Used by
    /// the polish LLM to do context-aware recognition of unseen STT
    /// mishearings ("main course ka IPO" → MACOBS, when MACOBS's example is
    /// "MACOBS ka IPO ka 12 hazaar batana"). Nullable for legacy rows.
    #[serde(default)]
    pub example_context: Option<String>,
    /// Term-type classification used by the polish prompt to reason from
    /// structured signals (acronym vs proper noun vs common word) instead
    /// of needing hardcoded exception lists. See `classify_term_type()`.
    #[serde(default)]
    pub term_type: Option<String>,
    /// LLM-distilled semantic description (1-2 sentences). Generated by
    /// Groq from observed examples and refined as more accumulate. Polish
    /// prompt uses this for the third matching layer (semantic alignment).
    /// Nullable for terms learned before migration 018 or when Groq is
    /// unavailable.
    #[serde(default)]
    pub meaning: Option<String>,
}

/// Classify a term's lexical shape into one of the polish-prompt categories.
///
/// The polish LLM uses this to reason about whether a transcript candidate
/// is *type-compatible* with the canonical. An acronym vocab entry should
/// not match a single common English word; a proper noun should match a
/// name-shaped token; a code identifier should match a digit/underscore-
/// bearing token; etc.
///
/// Cheap heuristic — same signals as `phonetics::jargon_score` but
/// returning a category instead of a numeric score. No LLM call, no
/// network. Conservative: when no signal fires we return "other" rather
/// than guess.
///
/// Categories:
///   "phrase"          — multi-word
///   "acronym"         — all-caps alphabetic, 2-8 chars (NASA, MACOBS, IPO)
///   "code_identifier" — contains digits, underscores, or hyphens (n8n, k8s, snake_case)
///   "brand"           — mixed case (iPhone, OpenAI, ClaudeCode)
///   "proper_noun"     — initial-cap + rest-lowercase, ≥4 chars (Anish, Vipassana)
///   "other"           — none of the above (likely generic / common word)
pub fn classify_term_type(term: &str) -> &'static str {
    let t = term.trim();
    if t.is_empty() {
        return "other";
    }

    // Multi-word → phrase (highest priority — overrides single-word checks)
    if t.contains(char::is_whitespace) {
        return "phrase";
    }

    let alpha_only = t.chars().all(|c| c.is_ascii_alphabetic());
    let has_lower = t.chars().any(|c| c.is_ascii_lowercase());
    let has_upper = t.chars().any(|c| c.is_ascii_uppercase());
    let has_digit = t.chars().any(|c| c.is_ascii_digit());
    let len = t.chars().count();
    let upper_after_first = t
        .chars()
        .enumerate()
        .any(|(i, c)| i > 0 && c.is_ascii_uppercase());

    // All-caps acronym: alphabetic, 2-8 chars, no lowercase
    if alpha_only && has_upper && !has_lower && (2..=8).contains(&len) {
        return "acronym";
    }
    // Code identifier: digits OR underscore OR hyphen
    if has_digit || t.contains('_') || t.contains('-') {
        return "code_identifier";
    }
    // Brand / mixed-case: uppercase AFTER position 0
    if has_lower && upper_after_first {
        return "brand";
    }
    // Proper noun: initial-cap, rest lowercase, ≥4 chars
    if alpha_only && len >= 4 {
        let first = t.chars().next().unwrap();
        let rest_lower = t.chars().skip(1).all(|c| c.is_ascii_lowercase());
        if first.is_ascii_uppercase() && rest_lower {
            return "proper_noun";
        }
    }
    "other"
}

/// Insert or strengthen a vocabulary term (language-agnostic — kept for
/// backward compatibility with manual-add and starred paths that don't
/// carry a language).  New code from the classifier should call
/// `upsert_for_language` instead so the term is bucketed correctly.
pub fn upsert(pool: &DbPool, user_id: &str, term: &str, bump: f64, source: &str) -> bool {
    upsert_inner(pool, user_id, term, bump, source, None, None)
}

/// Insert or strengthen a vocabulary term, recording the user's
/// `output_language` at the time of the sighting.  This is what the
/// learning pipeline calls so the keyterms slate can be filtered by
/// language at recording time (no Devanagari leaking into English-mode
/// Deepgram requests).
pub fn upsert_for_language(
    pool: &DbPool,
    user_id: &str,
    term: &str,
    bump: f64,
    source: &str,
    language: &str,
) -> bool {
    upsert_inner(pool, user_id, term, bump, source, Some(language), None)
}

/// Like `upsert_for_language` but also records an `example_context` — the
/// sentence (or snippet) the term was observed in at learning time. This
/// becomes part of the polish LLM's prompt context, enabling context-aware
/// recognition of unseen STT mishearings.
///
/// On repeat upserts:
///   • If the existing row has no example_context, the new one is set.
///   • If the existing row already has a context and the new context differs,
///     we keep the older one (first-observed wins for stability — the user's
///     earliest example is usually the most representative).
///   • Empty / whitespace-only context is treated as None.
pub fn upsert_for_language_with_context(
    pool: &DbPool,
    user_id: &str,
    term: &str,
    bump: f64,
    source: &str,
    language: &str,
    example_context: Option<&str>,
) -> bool {
    let ctx = example_context.map(str::trim).filter(|s| !s.is_empty());
    upsert_inner(pool, user_id, term, bump, source, Some(language), ctx)
}

fn upsert_inner(
    pool: &DbPool,
    user_id: &str,
    term: &str,
    bump: f64,
    source: &str,
    language: Option<&str>,
    example_context: Option<&str>,
) -> bool {
    let conn = match pool.get() {
        Ok(c) => c,
        Err(_) => return false,
    };
    let trimmed = term.trim();
    if trimmed.is_empty() {
        return false;
    }
    let now = now_ms();
    // Cap context to keep prompt size reasonable. 240 chars ≈ 60 tokens —
    // enough for one sentence, small enough that a vocab of 100 terms
    // adds < 1.5 KB to every polish prompt.
    const CONTEXT_MAX_CHARS: usize = 240;
    let trimmed_ctx: Option<String> = example_context.map(|c| {
        let s = c.trim();
        if s.chars().count() > CONTEXT_MAX_CHARS {
            s.chars().take(CONTEXT_MAX_CHARS).collect::<String>() + "…"
        } else {
            s.to_string()
        }
    });
    // Classify the term's lexical shape (acronym / brand / proper noun /
    // code identifier / phrase / other) so the polish prompt can render
    // structured, type-aware entries instead of bare tokens. Cheap
    // heuristic, no LLM call. Always recomputed (idempotent).
    let term_type = classify_term_type(trimmed);
    // ON CONFLICT for example_context: COALESCE keeps the first-observed
    // context (most representative; later sightings of the same term may
    // be in a generic sentence that strips meaning). term_type is always
    // refreshed because the classifier is deterministic — re-running it
    // never changes the answer for the same term.
    let n = match language {
        Some(lang) => conn.execute(
            "INSERT INTO vocabulary
                 (user_id, term, weight, use_count, last_used, source, language, example_context, term_type)
             VALUES (?1, ?2, ?3, 1, ?4, ?5, ?6, ?7, ?8)
             ON CONFLICT(user_id, term) DO UPDATE SET
                weight    = MIN(5.0, weight + ?3),
                use_count = use_count + 1,
                last_used = excluded.last_used,
                language  = excluded.language,
                example_context = COALESCE(vocabulary.example_context, excluded.example_context),
                term_type = excluded.term_type,
                source    = CASE
                              WHEN vocabulary.source = 'starred' THEN 'starred'
                              ELSE excluded.source
                            END",
            params![user_id, trimmed, bump, now, source, lang, trimmed_ctx, term_type],
        ),
        None => conn.execute(
            "INSERT INTO vocabulary
                 (user_id, term, weight, use_count, last_used, source, example_context, term_type)
             VALUES (?1, ?2, ?3, 1, ?4, ?5, ?6, ?7)
             ON CONFLICT(user_id, term) DO UPDATE SET
                weight    = MIN(5.0, weight + ?3),
                use_count = use_count + 1,
                last_used = excluded.last_used,
                example_context = COALESCE(vocabulary.example_context, excluded.example_context),
                term_type = excluded.term_type,
                source    = CASE
                              WHEN vocabulary.source = 'starred' THEN 'starred'
                              ELSE excluded.source
                            END",
            params![user_id, trimmed, bump, now, source, trimmed_ctx, term_type],
        ),
    };
    match n {
        Ok(rows) => {
            info!(
                "[vocab] upsert term={trimmed:?} bump={bump} lang={:?} rows={rows}",
                language,
            );
            rows > 0
        }
        Err(e) => {
            tracing::warn!("[vocab] upsert failed: {e}");
            false
        }
    }
}

/// Decrement weight on a negative signal (e.g. user reverted a learned term).
/// Removes the row when weight drops to or below 0.
pub fn demote(pool: &DbPool, user_id: &str, term: &str, penalty: f64) -> bool {
    let conn = match pool.get() {
        Ok(c) => c,
        Err(_) => return false,
    };
    let trimmed = term.trim();
    if trimmed.is_empty() {
        return false;
    }
    let updated = conn
        .execute(
            "UPDATE vocabulary SET weight = weight - ?3
           WHERE user_id = ?1 AND term = ?2",
            params![user_id, trimmed, penalty],
        )
        .unwrap_or(0);

    if updated == 0 {
        return false;
    }

    let removed = conn
        .execute(
            "DELETE FROM vocabulary
           WHERE user_id = ?1 AND term = ?2 AND weight <= 0.0 AND source != 'starred'",
            params![user_id, trimmed],
        )
        .unwrap_or(0);

    info!("[vocab] demote term={trimmed:?} penalty={penalty} removed={removed}");
    true
}

/// Top-N vocabulary terms by weight × recency.  Used to populate STT keyterms.
pub fn top_terms(pool: &DbPool, user_id: &str, limit: usize) -> Vec<VocabTerm> {
    let conn = match pool.get() {
        Ok(c) => c,
        Err(_) => return vec![],
    };
    let mut stmt = match conn.prepare(
        "SELECT term, weight, use_count, last_used, source,
                example_context, term_type, meaning
           FROM vocabulary
          WHERE user_id = ?1
          ORDER BY weight DESC, last_used DESC
          LIMIT ?2",
    ) {
        Ok(s) => s,
        Err(_) => return vec![],
    };
    stmt.query_map(params![user_id, limit as i64], |row| {
        Ok(VocabTerm {
            term: row.get(0)?,
            weight: row.get(1)?,
            use_count: row.get(2)?,
            last_used: row.get(3)?,
            source: row.get(4)?,
            example_context: row.get(5).ok(),
            term_type: row.get(6).ok(),
            meaning: row.get(7).ok(),
        })
    })
    .ok()
    .map(|rows| rows.filter_map(|r| r.ok()).collect())
    .unwrap_or_default()
}

/// Convenience: extract just the term strings, for STT API injection.
pub fn top_term_strings(pool: &DbPool, user_id: &str, limit: usize) -> Vec<String> {
    top_terms(pool, user_id, limit)
        .into_iter()
        .map(|t| t.term)
        .collect()
}

/// Top-N vocabulary terms scoped to a specific language.  Rows whose
/// `language` is NULL (legacy / language-agnostic) are always included so
/// the backfill from before migration 013 doesn't disappear from the
/// keyterms slate overnight.
pub fn top_term_strings_for_language(
    pool: &DbPool,
    user_id: &str,
    language: &str,
    limit: usize,
) -> Vec<String> {
    let conn = match pool.get() {
        Ok(c) => c,
        Err(_) => return vec![],
    };
    let mut stmt = match conn.prepare(
        "SELECT term FROM vocabulary
          WHERE user_id = ?1
            AND (language = ?2 OR language IS NULL)
          ORDER BY weight DESC, last_used DESC
          LIMIT ?3",
    ) {
        Ok(s) => s,
        Err(_) => return vec![],
    };
    stmt.query_map(params![user_id, language, limit as i64], |row| {
        row.get::<_, String>(0)
    })
    .ok()
    .map(|rows| rows.filter_map(|r| r.ok()).collect())
    .unwrap_or_default()
}

/// Threshold: number of new examples before triggering a meaning regeneration.
/// Smaller = more responsive (semantic understanding refines quickly), larger
/// = cheaper (fewer Groq calls). 3 is a balance — refreshes after every few
/// confirmed sightings without burning through budget.
pub const MEANING_REFRESH_THRESHOLD: i64 = 3;

/// Persist a freshly-generated meaning + reset the example counter so the
/// next refresh trigger fires after MEANING_REFRESH_THRESHOLD more examples.
/// Called fire-and-forget after the LLM completes meaning generation.
pub fn update_meaning(pool: &DbPool, user_id: &str, term: &str, meaning: &str) -> bool {
    let Ok(conn) = pool.get() else {
        return false;
    };
    let now = now_ms();
    let n = conn
        .execute(
            "UPDATE vocabulary
            SET meaning = ?3,
                meaning_updated_at = ?4,
                examples_since_meaning = 0
          WHERE user_id = ?1 AND term = ?2",
            params![user_id, term.trim(), meaning.trim(), now],
        )
        .unwrap_or(0);
    if n > 0 {
        info!(
            "[vocab-meaning] updated for {term:?} ({} chars)",
            meaning.trim().len()
        );
    }
    n > 0
}

/// Increment the per-term example counter. Called from the centroid-recompute
/// path on every new observed example. Returns the new counter value so the
/// caller can decide whether to trigger a meaning refresh.
pub fn bump_examples_since_meaning(pool: &DbPool, user_id: &str, term: &str) -> i64 {
    let Ok(conn) = pool.get() else {
        return 0;
    };
    let _ = conn.execute(
        "UPDATE vocabulary
            SET examples_since_meaning = examples_since_meaning + 1
          WHERE user_id = ?1 AND term = ?2",
        params![user_id, term.trim()],
    );
    conn.query_row(
        "SELECT examples_since_meaning FROM vocabulary
          WHERE user_id = ?1 AND term = ?2",
        params![user_id, term.trim()],
        |r| r.get::<_, i64>(0),
    )
    .unwrap_or(0)
}

/// Read the current stored meaning for a term, if any. Returns `None` when
/// the term doesn't exist or has never had a meaning generated. Used by the
/// meaning-refresh path to give the LLM the previous distillation as the
/// "keep what's still accurate" anchor.
pub fn get_meaning(pool: &DbPool, user_id: &str, term: &str) -> Option<String> {
    let conn = pool.get().ok()?;
    conn.query_row(
        "SELECT meaning FROM vocabulary
          WHERE user_id = ?1 AND term = ?2",
        params![user_id, term.trim()],
        |r| r.get::<_, Option<String>>(0),
    )
    .ok()
    .flatten()
    .filter(|s| !s.trim().is_empty())
}

/// True if the term's meaning needs (re)generation:
///   • meaning is NULL (never generated), OR
///   • examples_since_meaning >= MEANING_REFRESH_THRESHOLD
///
/// The caller spawns a Groq call only when this returns true, keeping the
/// LLM-cost cadence under control.
pub fn meaning_needs_refresh(pool: &DbPool, user_id: &str, term: &str) -> bool {
    let Ok(conn) = pool.get() else {
        return false;
    };
    conn.query_row(
        "SELECT meaning, examples_since_meaning FROM vocabulary
          WHERE user_id = ?1 AND term = ?2",
        params![user_id, term.trim()],
        |r| {
            let meaning: Option<String> = r.get(0)?;
            let count: i64 = r.get(1)?;
            Ok(meaning.is_none() || count >= MEANING_REFRESH_THRESHOLD)
        },
    )
    .unwrap_or(false)
}

/// Recompute missing `term_type` values for legacy rows that predate the
/// structured-vocabulary prompt. Cheap local repair run at startup.
pub fn backfill_missing_term_types(pool: &DbPool) -> usize {
    let Ok(conn) = pool.get() else {
        return 0;
    };
    let Ok(mut stmt) = conn.prepare(
        "SELECT user_id, term
           FROM vocabulary
          WHERE term_type IS NULL OR trim(term_type) = ''",
    ) else {
        return 0;
    };
    let rows: Vec<(String, String)> = stmt
        .query_map([], |row| Ok((row.get(0)?, row.get(1)?)))
        .ok()
        .map(|it| it.filter_map(|r| r.ok()).collect())
        .unwrap_or_default();
    drop(stmt);

    let mut repaired = 0;
    for (user_id, term) in rows {
        let term_type = classify_term_type(&term);
        repaired += conn
            .execute(
                "UPDATE vocabulary
                SET term_type = ?3
              WHERE user_id = ?1 AND term = ?2",
                params![user_id, term, term_type],
            )
            .unwrap_or(0);
    }
    repaired
}

/// Total count of vocabulary entries for a user (UI badge).
pub fn count(pool: &DbPool, user_id: &str) -> i64 {
    let conn = match pool.get() {
        Ok(c) => c,
        Err(_) => return 0,
    };
    conn.query_row(
        "SELECT COUNT(*) FROM vocabulary WHERE user_id = ?1",
        params![user_id],
        |r| r.get(0),
    )
    .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use r2d2_sqlite::SqliteConnectionManager;

    fn mem_pool() -> DbPool {
        let mgr = SqliteConnectionManager::memory();
        let pool = r2d2::Pool::builder().max_size(1).build(mgr).unwrap();
        // Minimal schema needed by these tests.
        let conn = pool.get().unwrap();
        conn.execute_batch(
            "CREATE TABLE local_user (id TEXT PRIMARY KEY);
             INSERT INTO local_user(id) VALUES ('u1');
             CREATE TABLE vocabulary (
                 user_id                 TEXT NOT NULL REFERENCES local_user(id),
                 term                    TEXT NOT NULL,
                 weight                  REAL NOT NULL DEFAULT 1.0,
                 use_count               INTEGER NOT NULL DEFAULT 1,
                 last_used               INTEGER NOT NULL,
                 source                  TEXT NOT NULL DEFAULT 'auto',
                 language                TEXT,
                 example_context         TEXT,
                 term_type               TEXT,
                 meaning                 TEXT,
                 meaning_updated_at      INTEGER,
                 examples_since_meaning  INTEGER NOT NULL DEFAULT 0,
                 UNIQUE(user_id, term)
             );",
        )
        .unwrap();
        pool
    }

    #[test]
    fn first_insert_creates_row_with_weight_one() {
        let pool = mem_pool();
        assert!(upsert(&pool, "u1", "n8n", 1.0, "auto"));
        let terms = top_terms(&pool, "u1", 10);
        assert_eq!(terms.len(), 1);
        assert_eq!(terms[0].term, "n8n");
        assert_eq!(terms[0].use_count, 1);
        assert!((terms[0].weight - 1.0).abs() < 1e-9);
    }

    #[test]
    fn repeat_upsert_bumps_weight_and_use_count() {
        let pool = mem_pool();
        upsert(&pool, "u1", "n8n", 1.0, "auto");
        upsert(&pool, "u1", "n8n", 1.0, "auto");
        let terms = top_terms(&pool, "u1", 10);
        assert_eq!(terms[0].use_count, 2);
        assert!(terms[0].weight > 1.0);
    }

    #[test]
    fn weight_capped_at_five() {
        let pool = mem_pool();
        for _ in 0..10 {
            upsert(&pool, "u1", "n8n", 1.0, "auto");
        }
        let terms = top_terms(&pool, "u1", 10);
        assert!(terms[0].weight <= 5.0 + 1e-9);
    }

    #[test]
    fn demote_drops_row_when_weight_zero() {
        let pool = mem_pool();
        upsert(&pool, "u1", "noisy", 1.0, "auto");
        assert_eq!(count(&pool, "u1"), 1);
        assert!(demote(&pool, "u1", "noisy", 1.5)); // weight goes negative
        assert_eq!(count(&pool, "u1"), 0);
    }

    #[test]
    fn demote_does_not_drop_starred_terms() {
        let pool = mem_pool();
        upsert(&pool, "u1", "MyName", 1.0, "starred");
        demote(&pool, "u1", "MyName", 5.0);
        assert_eq!(count(&pool, "u1"), 1, "starred terms must survive demotion");
    }

    #[test]
    fn empty_term_is_ignored() {
        let pool = mem_pool();
        assert!(!upsert(&pool, "u1", "  ", 1.0, "auto"));
        assert_eq!(count(&pool, "u1"), 0);
    }

    #[test]
    fn per_language_filter_only_returns_matching_or_null() {
        let pool = mem_pool();
        // Pre-013 row (language = NULL) — should always show.
        upsert(&pool, "u1", "legacy_term", 2.0, "auto");
        // English-bucketed term.
        upsert_for_language(&pool, "u1", "english_term", 1.0, "auto", "english");
        // Hinglish-bucketed term.
        upsert_for_language(&pool, "u1", "hinglish_term", 1.0, "auto", "hinglish");

        let english = top_term_strings_for_language(&pool, "u1", "english", 10);
        assert!(
            english.contains(&"legacy_term".into()),
            "legacy term must be returned"
        );
        assert!(
            english.contains(&"english_term".into()),
            "english bucket must be returned"
        );
        assert!(
            !english.contains(&"hinglish_term".into()),
            "hinglish term must NOT leak into english"
        );

        let hinglish = top_term_strings_for_language(&pool, "u1", "hinglish", 10);
        assert!(hinglish.contains(&"legacy_term".into()));
        assert!(hinglish.contains(&"hinglish_term".into()));
        assert!(!hinglish.contains(&"english_term".into()));
    }

    // ── Term type classifier ──────────────────────────────────────────────────

    #[test]
    fn classify_term_type_acronyms() {
        assert_eq!(classify_term_type("MACOBS"), "acronym");
        assert_eq!(classify_term_type("NASA"), "acronym");
        assert_eq!(classify_term_type("IPO"), "acronym");
        assert_eq!(classify_term_type("FBI"), "acronym");
        assert_eq!(classify_term_type("EMIAC"), "acronym");
    }

    #[test]
    fn classify_term_type_proper_nouns() {
        assert_eq!(classify_term_type("Anish"), "proper_noun");
        assert_eq!(classify_term_type("Vipassana"), "proper_noun");
        assert_eq!(classify_term_type("Cursor"), "proper_noun");
        assert_eq!(classify_term_type("Linear"), "proper_noun");
    }

    #[test]
    fn classify_term_type_brands_mixed_case() {
        assert_eq!(classify_term_type("iPhone"), "brand");
        assert_eq!(classify_term_type("OpenAI"), "brand");
        assert_eq!(classify_term_type("ClaudeCode"), "brand");
    }

    #[test]
    fn classify_term_type_code_identifiers() {
        assert_eq!(classify_term_type("n8n"), "code_identifier");
        assert_eq!(classify_term_type("k8s"), "code_identifier");
        assert_eq!(classify_term_type("snake_case"), "code_identifier");
        assert_eq!(classify_term_type("kebab-case"), "code_identifier");
    }

    #[test]
    fn classify_term_type_phrases() {
        assert_eq!(classify_term_type("Cloud Code"), "phrase");
        assert_eq!(classify_term_type("Hello World Inc."), "phrase");
    }

    #[test]
    fn classify_term_type_falls_back_to_other() {
        // The bug-class words: common single-case words don't have a strong
        // type signal, so they fall into "other". The polish prompt then
        // renders them without a type tag and the LLM treats them with extra
        // care. (In practice users shouldn't add these as vocab — but if they
        // do, we don't pretend they're jargon.)
        assert_eq!(classify_term_type("hello"), "other");
        assert_eq!(classify_term_type("world"), "other");
        assert_eq!(classify_term_type("a"), "other"); // too short for proper_noun
        assert_eq!(classify_term_type("the"), "other"); // sentence-case but only 3 chars
    }

    #[test]
    fn classify_term_type_empty_safe() {
        assert_eq!(classify_term_type(""), "other");
        assert_eq!(classify_term_type("   "), "other");
    }

    #[test]
    fn upsert_writes_term_type_to_db() {
        let pool = mem_pool();
        upsert_for_language(&pool, "u1", "MACOBS", 1.0, "auto", "english");
        upsert_for_language(&pool, "u1", "Anish", 1.0, "auto", "english");
        upsert_for_language(&pool, "u1", "n8n", 1.0, "auto", "english");
        let terms = top_terms(&pool, "u1", 10);
        let by_term: std::collections::HashMap<_, _> = terms
            .iter()
            .map(|t| (t.term.as_str(), t.term_type.as_deref()))
            .collect();
        assert_eq!(by_term.get("MACOBS").and_then(|x| *x), Some("acronym"));
        assert_eq!(by_term.get("Anish").and_then(|x| *x), Some("proper_noun"));
        assert_eq!(by_term.get("n8n").and_then(|x| *x), Some("code_identifier"));
    }

    #[test]
    fn upsert_with_context_stores_example() {
        let pool = mem_pool();
        assert!(upsert_for_language_with_context(
            &pool,
            "u1",
            "MACOBS",
            1.0,
            "auto",
            "hinglish",
            Some("MACOBS ka IPO ka 12 hazaar batana"),
        ));
        let terms = top_terms(&pool, "u1", 10);
        assert_eq!(terms.len(), 1);
        assert_eq!(terms[0].term, "MACOBS");
        assert_eq!(
            terms[0].example_context.as_deref(),
            Some("MACOBS ka IPO ka 12 hazaar batana"),
        );
    }

    #[test]
    fn first_observed_context_wins_on_repeat_upsert() {
        // Repeat sightings shouldn't overwrite the original context — the
        // first example is usually the most representative; later sentences
        // may strip the term out of its meaningful surroundings.
        let pool = mem_pool();
        upsert_for_language_with_context(
            &pool,
            "u1",
            "MACOBS",
            1.0,
            "auto",
            "hinglish",
            Some("MACOBS ka IPO ka 12 hazaar batana"),
        );
        upsert_for_language_with_context(
            &pool,
            "u1",
            "MACOBS",
            1.0,
            "auto",
            "hinglish",
            Some("yes"), // a stripped-down later example
        );
        let terms = top_terms(&pool, "u1", 10);
        assert_eq!(
            terms[0].example_context.as_deref(),
            Some("MACOBS ka IPO ka 12 hazaar batana"),
            "first-observed context should be preserved",
        );
    }

    #[test]
    fn empty_context_treated_as_none() {
        let pool = mem_pool();
        upsert_for_language_with_context(
            &pool,
            "u1",
            "n8n",
            1.0,
            "auto",
            "english",
            Some("   "), // whitespace only
        );
        assert!(top_terms(&pool, "u1", 10)[0].example_context.is_none());
    }

    #[test]
    fn long_context_is_capped() {
        let pool = mem_pool();
        let long = "x".repeat(500);
        upsert_for_language_with_context(&pool, "u1", "TERM", 1.0, "auto", "english", Some(&long));
        let stored = top_terms(&pool, "u1", 10)[0]
            .example_context
            .clone()
            .unwrap();
        // Capped at ~240 chars + ellipsis.
        assert!(
            stored.chars().count() <= 241,
            "got {}",
            stored.chars().count()
        );
        assert!(stored.ends_with('…'));
    }

    #[test]
    fn top_terms_orders_by_weight_desc() {
        let pool = mem_pool();
        upsert(&pool, "u1", "low", 1.0, "auto");
        upsert(&pool, "u1", "high", 1.0, "auto");
        upsert(&pool, "u1", "high", 1.0, "auto");
        let terms = top_term_strings(&pool, "u1", 10);
        assert_eq!(terms[0], "high");
        assert_eq!(terms[1], "low");
    }

    #[test]
    fn meaning_round_trip_through_top_terms() {
        let pool = mem_pool();
        upsert(&pool, "u1", "MACOBS", 1.0, "auto");
        assert!(
            get_meaning(&pool, "u1", "MACOBS").is_none(),
            "meaning is None until generated"
        );
        assert!(update_meaning(
            &pool,
            "u1",
            "MACOBS",
            "An Indian SME stock acronym."
        ));
        assert_eq!(
            get_meaning(&pool, "u1", "MACOBS").as_deref(),
            Some("An Indian SME stock acronym.")
        );
        // Round-trips through top_terms (the path the polish prompt uses).
        let terms = top_terms(&pool, "u1", 10);
        assert_eq!(terms.len(), 1);
        assert_eq!(
            terms[0].meaning.as_deref(),
            Some("An Indian SME stock acronym.")
        );
    }

    #[test]
    fn update_meaning_resets_examples_counter() {
        let pool = mem_pool();
        upsert(&pool, "u1", "MACOBS", 1.0, "auto");
        // Bump the counter past the threshold.
        bump_examples_since_meaning(&pool, "u1", "MACOBS");
        bump_examples_since_meaning(&pool, "u1", "MACOBS");
        bump_examples_since_meaning(&pool, "u1", "MACOBS");
        assert!(
            meaning_needs_refresh(&pool, "u1", "MACOBS"),
            "with no meaning + count above threshold, refresh is needed"
        );
        // After persisting a meaning, counter resets and refresh quiets down.
        assert!(update_meaning(&pool, "u1", "MACOBS", "Meaning text"));
        assert!(
            !meaning_needs_refresh(&pool, "u1", "MACOBS"),
            "fresh meaning + reset counter ⇒ no refresh needed"
        );
    }

    #[test]
    fn meaning_needs_refresh_at_threshold() {
        let pool = mem_pool();
        upsert(&pool, "u1", "TERM", 1.0, "auto");
        update_meaning(&pool, "u1", "TERM", "first description");
        // Below threshold — quiet.
        for _ in 0..(MEANING_REFRESH_THRESHOLD - 1) {
            bump_examples_since_meaning(&pool, "u1", "TERM");
        }
        assert!(!meaning_needs_refresh(&pool, "u1", "TERM"));
        // Crossing threshold — fires.
        bump_examples_since_meaning(&pool, "u1", "TERM");
        assert!(meaning_needs_refresh(&pool, "u1", "TERM"));
    }

    #[test]
    fn meaning_needs_refresh_when_never_generated() {
        let pool = mem_pool();
        upsert(&pool, "u1", "FRESH", 1.0, "auto");
        assert!(
            meaning_needs_refresh(&pool, "u1", "FRESH"),
            "a brand-new term with no meaning always needs refresh"
        );
    }
}
